version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: infra/backend.Dockerfile
    env_file:
      - ../backend/.env.example
    environment:
      K2_API_URL: http://backend:8000/mock-k2
      K2_API_KEY: dev-token
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ..
      dockerfile: infra/frontend.Dockerfile
    environment:
      VITE_API_BASE: http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
